# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mission-with-RxSwift-and-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mission-with-RxSwift-and-MVVM
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxViewController'

end
